
@startuml
'https://plantuml.com/class-diagram

class ChatFragment extends Fragment {
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState){}

    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {}

}


class FightFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}


    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {}


}


class InventoryFragment extends Fragment {


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}

    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {}


}

class MapFragment extends Fragment {
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {}

    private Pair<Integer, Integer> find_title_coords(ImageView v, ImageView[][] p){}

}

class MenuFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}


    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {}
}

class RegistrationFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}

    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {}
}

class ResearchTreeFragment extends Fragment {
    public static HashMap<Research, TextView> research_hash_map;
    public static HashMap<TextView, Research> research_hash_map1;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}

    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {}
}

class SpellCreationFragment extends Fragment {
    private Element element=MainActivity.elements.get(0);
    private Type type=MainActivity.types.get(0);
    private Form form=MainActivity.forms.get(0);
    private ManaChannel mana_channel=MainActivity.mana_channels.get(0);
    private ManaReservoir mana_reservoir=MainActivity.mana_reservoirs.get(0);
    private String name;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}

    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {}


}

class SpellsFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}

    @Override
    public void onViewCreated(@NonNull @NotNull View view, @Nullable @org.jetbrains.annotations.Nullable Bundle savedInstanceState) {}
}


class StatusBarFragment extends Fragment {
    private static ProgressBar mana_bar;
    private static ProgressBar health_bar;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {}

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {}

    public static void update() {}
}
@enduml

@startuml
class SpellsViewHolder extends RecyclerView.ViewHolder{
    TextView name;
    public SpellsViewHolder(@NonNull @NotNull View itemView) {}
}

class SpellsAdapter extends RecyclerView.Adapter{
    ArrayList<Spell> spells;

    public SpellsAdapter(ArrayList<Spell> spells) {}

    @NonNull
    @NotNull
    @Override
    public SpellsViewHolder onCreateViewHolder(@NonNull @NotNull ViewGroup parent, int viewType) {}

    @Override
    public void onBindViewHolder(@NonNull @NotNull SpellsFragment.SpellsAdapter.SpellsViewHolder holder, int position) {}

    @Override
    public int getItemCount() {}
}

class ViewHolder extends RecyclerView.ViewHolder{
    TextView comp;
    public ViewHolder(@NonNull @NotNull View itemView) {}
}

class SpellAdapter<T extends Component> extends RecyclerView.Adapter{
    private final ArrayList<T> data=new ArrayList<>();

    public SpellAdapter(ArrayList<T> data) {}

    @NonNull
    @NotNull
    @Override
    public SpellCreationFragment.SpellAdapter.ViewHolder onCreateViewHolder(@NonNull @NotNull ViewGroup parent, int viewType) {}

    @Override
    public void onBindViewHolder(@NonNull @NotNull SpellCreationFragment.SpellAdapter.ViewHolder holder, int position) {}

    @Override
    public int getItemCount() {}
}

class SpellsAdapter extends RecyclerView.Adapter {
    ArrayList<Spell> data = new ArrayList<>();

    public SpellsAdapter(ArrayList<Spell> data) {}

    @NonNull
    @NotNull
    @Override
    public SpellViewHolder onCreateViewHolder(@NonNull @NotNull ViewGroup parent, int viewType) {}

    @Override
    public void onBindViewHolder(@NonNull @NotNull FightFragment.SpellsAdapter.SpellViewHolder holder, int position) {}

    @Override
    public int getItemCount() {}


}

class SpellViewHolder extends RecyclerView.ViewHolder {
    TextView name;

    public SpellViewHolder(@NonNull @NotNull View itemView) {}
}
class InventoryAdapter extends RecyclerView.Adapter{
    private final ArrayList<Item> data=new ArrayList<>();

    public InventoryAdapter(ArrayList<Item> data) {}



    @NonNull
    @NotNull
    @Override
    public InventoryFragment.InventoryAdapter.InvenoryViewHolder onCreateViewHolder(@NonNull @NotNull ViewGroup parent, int viewType) {}

    @Override
    public void onBindViewHolder(@NonNull @NotNull InventoryFragment.InventoryAdapter.InvenoryViewHolder holder, int position) {}

    @Override
    public int getItemCount() {}
}

class InvenoryViewHolder extends RecyclerView.ViewHolder{
    TextView name;
    public InvenoryViewHolder(@NonNull @NotNull View itemView) {}
}
class ChatAdapter extends RecyclerView.Adapter{

    ArrayList<Message> data;

    public ChatAdapter(ArrayList<Message> messages){}

    @NonNull
    @NotNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull @NotNull ViewGroup parent, int viewType) {}

    @Override
    public void onBindViewHolder(@NonNull @NotNull ChatFragment.ChatAdapter.ViewHolder holder, int position) {}

    @Override
    public int getItemCount() {}
}

class ViewHolder extends RecyclerView.ViewHolder{
    TextView user, message, time;
    public ViewHolder(@NonNull @NotNull View itemView) {}
}
@enduml