@startuml
'https://plantuml.com/class-diagram

class Component {
    private String name;
    private boolean available;

    public Component(String name, boolean available) {}
}

class Element extends Component{
    private int element, base_damage;

    public Element(String name, int element, int base_damage, boolean available) {}

    public Element(Element element){}
}

class Form extends Component {
    private final int form;

    public Form(String name, int form, boolean available) {}

    public Form(Form form){}
}

class ManaChannel extends Component {
    private final int mps;

    public ManaChannel(String name, int mps, boolean available) {}

    public ManaChannel(ManaChannel manaChannel){}

    public int getMps() {}
}

class ManaReservoir extends Component {
    private final int volume;

    public ManaReservoir(String name, int volume, boolean available) {}

    public ManaReservoir(ManaReservoir manaReservoir){}
}

class Spell implements Serializable {
    private int mana_consumption, damage, lasting_time;
    private Element element;
    private Type type;
    private Form form;
    private ManaChannel manaChannel;
    private ManaReservoir manaReservoir;
    private String name;

    public Spell(Element element, Type type, Form form, ManaChannel manaChannel, ManaReservoir manaReservoir, String name) {}

    public Spell(Spell spell){}

    public void affect (Enemy enemy){}

    public void consume_mana(){}
}

class Type extends Component {
    private final int type;

    public Type(String name, int type, boolean available) {}

    public Type(Type type){}
}


@enduml