@startuml
'https://plantuml.com/class-diagram
interface A{
    @GET("/get_messages")
    Call<ArrayList<Message>> get_messages();

    @POST("/put_message")
    Call<String> put_message(@Query("message") String message);

    @POST("/register")
    Call<String> register(@Query("login") String login, @Query("password") String password);

    @POST("/log_in")
    Call<String> log_in(@Query("login") String login, @Query("password") String password);

    @POST("/log_out")
    Call<String> log_out(@Query("login") String login);

    @GET("/is_registered")
    Call<Boolean> is_registered(@Query("login") String login);

    @GET("/is_logged_in")
    Call<Boolean> is_logged_in(@Query("login") String login);
}
class Message{
    @Expose
    public String message;
    @Expose
    public String user;
    @Expose
    public Date date;

    public String toString() {}
}

class Music {
    private MediaPlayer mPlayer;

    public Music(){}

    public void stop() {}

    public void start(Context c, int track) {}
}

class Research {
    private final ArrayList<Research> required_researches;
    private final String name;
    private final int cost, tier, effect;
    private boolean researched, available;

    public Research(ArrayList<Research> required_researches, String name, int cost, int tier, int effect, boolean researched, boolean available) {}

    public void enable() {}

    public void affect(Player player){}
}

class User {
    private String login;
    private int password;
    private boolean logged_in;

    public User(String login, String password) {}

    public boolean try_password(String password) {}

    public void log_in() {}

    public void log_out() {}

    public boolean equals(Object o) {}

    public int hashCode() {}
}

@enduml